EXPOSURE_TO_CASE = 11
EXPOSURE_TO_ADMISSION = 11
EXPOSURE_TO_SEROPOSITIVE = 15
EXPOSURE_TO_DEATH = 24

CASE_TO_DEATH = EXPOSURE_TO_DEATH - EXPOSURE_TO_CASE
PCR_TO_SERO = EXPOSURE_TO_SEROPOSITIVE - EXPOSURE_TO_CASE

ADMISSION_TO_SERO = EXPOSURE_TO_SEROPOSITIVE - EXPOSURE_TO_ADMISSION
ADMISSION_TO_DEATH = EXPOSURE_TO_DEATH - EXPOSURE_TO_ADMISSION

SERO_TO_DEATH = EXPOSURE_TO_DEATH - EXPOSURE_TO_SEROPOSITIVE
